/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.palerique.elasticsearch.poc;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
